# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180524_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_zip',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
