# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_address_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_contact_person',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Контактное лицо'),
        ),
    ]
