# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180529_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_city',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_country',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_flat',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_house',
            field=models.CharField(max_length=32, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_region',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_street',
            field=models.CharField(max_length=32, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_zip',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='type',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='type',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_usage',
            field=models.CharField(choices=[('PAYM', 'Оплата'), ('DELI', 'Доставка')], default=None, max_length=12, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='type',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
