# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180529_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.CharField(choices=[('NON', 'Не указано'), ('SQM', 'За м²'), ('RNM', 'За м. пог.'), ('UNI', 'За штуку'), ('PAC', 'За упаковку')], default='NON', max_length=5, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_BIK',
            field=models.CharField(max_length=9, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_corr_account',
            field=models.CharField(max_length=20, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_email',
            field=models.EmailField(max_length=64, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_firstname',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_phone',
            field=models.CharField(max_length=48, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('CONF', 'Заказ сформирован'), ('DELD', 'Доставляется'), ('RECD', 'Выполнен'), ('CANC', 'Заказ отменён')], default='NEW', max_length=4, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_INN',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_KPP',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_OGRN',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='ОРГН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_OKPO',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_checking_account',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_phone',
            field=models.CharField(max_length=48, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('NON', 'Не указано'), ('OWN', 'Компания-аватар'), ('MAN', 'Производитель'), ('PRO', 'Поставщик'), ('PRT', 'Компания-партнёр'), ('CLI', 'Компания-клиент')], default='NON', max_length=4, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_article',
            field=models.CharField(max_length=32, verbose_name='Артикл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
