# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180529_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_email',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_website',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Сайт'),
        ),
    ]
