# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180529_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_zip',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Индекс'),
        ),
    ]
