# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180530_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_city1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_country1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_region1',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.AddressCity'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.AddressCountry'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.AddressRegion'),
        ),
    ]
