# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180602_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['bank_name'], 'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['c_firstname'], 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-updated'], 'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['org_name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_manufacturer'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
