# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20180602_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.Order'),
        ),
    ]
