# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180602_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Размер платежа'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.Order'),
        ),
    ]
