# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20180603_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresscountry',
            name='is_active',
        ),
    ]
