# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_addresscountry_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresscity',
            options={'verbose_name': 'Населённый пункт', 'verbose_name_plural': 'Города и населённые пункты'},
        ),
    ]
