# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_category_cat_alt_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_alt_id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
