# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20180603_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_alt_id', 'cat_alt_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='cat_alt_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Имя родителя'),
        ),
    ]
