# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 13:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_remove_organization_org_legal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'Размер должен быть положительным числом'), django.core.validators.DecimalValidator(10, 2)], verbose_name='Размер платежа'),
        ),
    ]
